### ISSUE TITLE
Give Lilly A "Hire Me!" Banner

### ISSUE THREAD

**Issue by taylorperkins** [NSS-Data-Analytics-Cohort-2/NSS-Data-Analytics-Cohort-2.github.io#22]
Lilly is actively job seeking! Please update the Website google sheet "Is Job Searching" field to TRUE for Lilly. Then, update the `cohort.json` file using the `Make JSON.ipynb`. Once that is done, check it out on your computer locally and make sure it is looking as you expected. 
See the videos I sent for some instruction on how to do this! Thanks!

**Comment by landrybutler** [comment]
Thanks. I'll work on this and let you know if any questions.

**Comment by landrybutler** [comment]
This is done. Will submit pull request for confirmation and merge.
