### ISSUE TITLE
Update Matt Barnes and Christina Hmun Capstone Video

### ISSUE THREAD

**Issue by taylorperkins** [NSS-Data-Analytics-Cohort-2/NSS-Data-Analytics-Cohort-2.github.io#23]
Mandy has uploaded the new videos to youtube. The updated links are in the "For Staff - Youtube Links" google sheet. These 2 youtube links will need to be copied over to the "Website" google sheet. Then, you will want to re-download the google sheet, and re-run the "Make JSON.ipynb"

**Comment by landrybutler** [comment]
This is done. Will submit pull request for confirmation and merge.
