### ISSUE TITLE
Deploy the website

### ISSUE THREAD

**Issue by taylorperkins** [NSS-Data-Analytics-Cohort-2/NSS-Data-Analytics-Cohort-2.github.io#6]
Hey @MaryLvV 
Haven't done this before! Any tips/pointers?

**Comment by MaryLvV** [comment]
it’s pretty straightforward- go to [site](https://NSS-Data-Analytics-Cohort-2.github.io )

**Comment by taylorperkins** [comment]
Well perfect! Marking as done
